name: Deploy to AKS

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  deploy:
    name: Deploy to AKS via HELM
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: max
          cluster-name: max-demo

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Prepare namespace for Helm ownership
        run: |
          kubectl get ns wordpress >/dev/null 2>&1 || kubectl create ns wordpress
          kubectl label ns wordpress app.kubernetes.io/managed-by=Helm --overwrite
          kubectl annotate ns wordpress meta.helm.sh/release-name=wordpress --overwrite
          kubectl annotate ns wordpress meta.helm.sh/release-namespace=wordpress --overwrite
            
      - name: Deploy inline (Helm)
        run: |
          echo "Deploying Helm"
          helm upgrade --install wordpress ./helm/wordpress \
            --namespace wordpress \
            --create-namespace